# Copyright 2026 Quantova Inc
# SPDX-License-Identifier: Apache-2.0 OR MIT
name: ci
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          path: Q-Oracle
          persist-credentials: false
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          repository: Quantova/q-prover
          ref: 98a80c816e9d0287ff7c1ab13b8a0dff21d77677
          path: q-prover
          persist-credentials: false
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          repository: Quantova/Q-Lightclient
          ref: 251424da8b4c73ea9cf3f0c83de814e3474fb90f
          path: Q-Lightclient
          persist-credentials: false
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          repository: Quantova/QRC-CONSENSUS
          ref: 213f177951f8d470dff13966f9e8753a3836dcc5
          path: QRC-CONSENSUS
          persist-credentials: false
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          repository: Quantova/Quantova-Chain
          ref: fa54015db8fcf34638d82809fe1a0309433152d1
          path: Quantova-Chain
          persist-credentials: false
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          repository: Quantova/QCore.rs
          ref: cce9ea1ec4309cf3db7b1bddbb6c4073e55af8e0
          path: QCore.rs
          persist-credentials: false
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          repository: Quantova/QVM
          ref: ea4cb474557b206566f144ca9c74b37b2dfd1a9f
          path: QVM
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@2c7215f132e9ebf062739d9130488b56d53c060c # master
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: fmt
        working-directory: Q-Oracle
        run: cargo fmt --all -- --check
      - name: clippy
        working-directory: Q-Oracle
        run: cargo clippy --all-targets --all-features --locked -- -D warnings
      - name: test
        working-directory: Q-Oracle
        run: cargo test --all-features --locked
