# Copyright 2026 Quantova Inc
# SPDX-License-Identifier: Apache-2.0 OR MIT
name: ci
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          path: Q-Oracle
          persist-credentials: false
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          repository: Quantova/q-prover
          ref: c0853314ae86c81d20830fa324397e50c7993336
          path: q-prover
          persist-credentials: false
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          repository: Quantova/Q-Lightclient
          ref: a7ea1427256630f2ee911fc10c30c4edf24505b8
          path: Q-Lightclient
          persist-credentials: false
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          repository: Quantova/QRC-CONSENSUS
          ref: 70e8c3a77ef3c427f8b8d60150776870d725020f
          path: QRC-CONSENSUS
          persist-credentials: false
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          repository: Quantova/Quantova-Chain
          ref: 77cb3fbc1786a3f9731ea8e8dcd26fe2eff1a355
          path: Quantova-Chain
          persist-credentials: false
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          repository: Quantova/QCore.rs
          ref: 51fc6f93554be10ed9f32f7a5c268e3e5bacc672
          path: QCore.rs
          persist-credentials: false
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          repository: Quantova/QVM
          ref: df3832375dd90e7cdad6038e512c0485b4480388
          path: QVM
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@2c7215f132e9ebf062739d9130488b56d53c060c # master
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: fmt
        working-directory: Q-Oracle
        run: cargo fmt --all -- --check
      - name: clippy
        working-directory: Q-Oracle
        run: cargo clippy --all-targets --all-features --locked -- -D warnings
      - name: test
        working-directory: Q-Oracle
        run: cargo test --all-features --locked
